### ISSUE TITLE
Support for image in text editors

### ISSUE THREAD

**Issue by XcrossD** [polonel/trudesk#122]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

Would it be possible to add support for images to the text editor so that users can add images? Sometimes it is more convenient to just upload a picture than to describe an issue in text. Ideally it would be similar to what github is using, but I can see adding images as attachment working too.

**Comment by polonel** [comment]
This is something I've wanted to implement but haven't gotten around to doing yet. It's a needed feature.

**Comment by oDevArc** [comment]
yes this would be a very useful feature

you could create an button/api to upload a desktop picture into a folder in the webserver so it could be linked like in standard webmail app OR can encode picture to text in base64 ? 

I think this is the weakness of all web based app : picture into the text instead of attachment

**Comment by polonel** [comment]
New image uploads support drag & drop and paste from clipboard. Currently on develop for testing. Is included in 1.0.6
