### ISSUE TITLE
[FEATURE] Add due date to tickets

### ISSUE THREAD

**Issue by xxdxhxx** [polonel/trudesk#141]
Hello,
I would love the ability to put a due date on tickets.  The SLA is fine for some types of tickets, but for others it does not fit.  
We use tickets for projects, and due dates are vital to this.
Would also be amazing to add color to tickets in the ticket view so you can use color to group things visually.

Thanks for the awesome product and work you all do.

**Comment by polonel** [comment]
I understand the need for this and I will add it. Some other systems need to be handled before this can work correctly. It should be implemented in a way that it doesn't affect the SLA times and with the current implementation, If I mark the ticket overdue because the due date has elapsed it will confuse the SLA timers because the ticket will already be marked as overdue.

It is planned.

**Comment by polonel** [comment]
Included in v1.0.11 (unreleased)
