### ISSUE TITLE
[API/Miscellanous] Date object is not correct

### ISSUE THREAD

**Issue by LuigiElleBalotta** [polonel/trudesk#184]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ x] BUG 
- [ ] FEATURE

**What happened**:
Italy is at +1 timezone. By the way with the winter time we are +2.
If i make an API request to get a ticket, the Date object is correct only if the offset is +0.
In order to display the correct date i had to make an hotfix in my asp.net core server, I add the offset to the trudesk date object manually

Example of offset parameter: "p02" or "m02" => p is for + and m is for - (this because i can't send "+" char into query string)

```csharp
public async Task<ActionResult> Dettaglio(string id, string offset)
        {
            TrudeskManager trudesk = GetTrudeskInstance();
            Ticket t = new Ticket();
            if (!string.IsNullOrWhiteSpace(id))
            {
                var response = await trudesk.GetTicket(id);

                t = response.ticket;

                if (!string.IsNullOrWhiteSpace(offset))
                {
                    t.offset = offset;

                    char sign = char.Parse(offset.Substring(0, 1));

                    int timeOffset = int.Parse(offset.Substring(1, offset.Length - 1));
                    if (sign == 'p')
                    {
                        t.date = t.date.AddHours(timeOffset);
                        foreach (Comment c in t.comments)
                            c.date = c.date.AddHours(timeOffset);
                        foreach (History h in t.history)
                            h.date = h.date.AddHours(timeOffset);
                    }
                    else
                    {
                        t.date = t.date.AddHours(-(timeOffset));
                        foreach (Comment c in t.comments)
                            c.date = c.date.AddHours(-timeOffset);
                        foreach (History h in t.history)
                            h.date = h.date.AddHours(-timeOffset);
                    }
                }
            }

            return View("Dettaglio", t);
        }
```

**What did you expect to happen**:
I expect to see the correct date

**How to reproduce it (as minimally and precisely as possible)**:
Explained upper

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by LuigiElleBalotta** [comment]
To see the api:
https://github.com/LuigiElleBalotta/TrudeskNetCore

**Comment by LuigiElleBalotta** [comment]
My suggestion is to modify the settings logic:
- The timezone should be at user level with a default value that can be set in the settings panel. In simple terms, change the meaning of this setting:
![timezone](https://user-images.githubusercontent.com/16773213/55793351-ff9ac880-5ac2-11e9-8609-e2fe2924a789.PNG)

**Comment by LuigiElleBalotta** [comment]
- Tickets were created in 1.0.6
- Through API

The problem anyway is that in our company (and this case can be applied to most of big companies) we have more than 1 branch in different timezone (our example is Singapore, Shanghai, Houston, Italy)
The C# code attacched some comment up fix this issue, since it seems that Trudesk give the +0 DateTime Object offset. But i think this should be done in Trudesk, i should not modify data from API to get the real result

**Comment by 0x3333** [comment]
Just my 2 cents... 

I had a similar problem years ago, but with Java. The default date object type doesnt included timezones, so if a client is in a different time zone, the date get a invalid offset when sent to/from server. 

We have 2 options, use a object type that encapsulates the timezone, so it get correctly handled by the server, or define a server default timezone, and offset accordingly in the client, in my case, we used the later, as it was easier, otherwise we had to change our database type.

**Comment by polonel** [comment]
All server dates are stored UTC+0

The Trudesk web UI offsets based on the timezone setting defined in the
general settings panel.

**Comment by LuigiElleBalotta** [comment]
@polonel are you ok with me to set the timezone at department/branch level and not globally?

**Comment by polonel** [comment]
The global timezone is current and will respect the correct +1 and +2 based on time of year. The issue you're seeing is I don't apply the offset to the API query, only the UI. The issue comes from the API is a raw dump from the database. I alter any information on the client instead of on the server. This allows the client to implement the data as they see fit. 

Ex: A third party is developing a tool against your trudesk instance. They see you have the timezone set to +1 and configure their offset based on your current setting. You then change your timezone setting and the third party has to change their offset. If they always receive the data as +0, then no matter what timezone setting you apply on the WebUI they will always get the data as +0.

You could do the same thing I'm doing on the Web UI, and that is using `moment-timezone` to parse the correct timezone date from the raw API data.
