### ISSUE TITLE
"User" role is unavailable in the drop-down in the Customer edit modal window

### ISSUE THREAD

**Issue by obutov** [polonel/trudesk#195]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**: Role drop-down is missing "User" option when editing Customer record from the Accounts>Customers view. When a previously created account with "User" role is opened for editing, role dropdown is cleared out and the only selection is "Users" role. Once the "Users" role is selected and saved, the account cannot be edited from the same modal. The only way to edit the account is by deleting it and then recreating it from scratch. If the account has a ticket linked, delete/recreate cannot be performed, hence Admin is unable to update the account. Neither can the user update the account, as saving Profile updates by the user is failing with "Not Authorized for this API call."
I'm stuck now where I cannot update account info, nor can I recreate the account as the test user entered a ticket into the system and cannot be deleted. There's also no option to permanently delete tickets, hence users with any tickets in the system cannot ever be deleted.

**What did you expect to happen**: "User" role should be visible in the Account Edit modal. "Users" role should be hidden to avoid confusion.

**How to reproduce it (as minimally and precisely as possible)**: Navigate to Accounts>Customers, select an account with Role = User. Try selecting the "User" role again. Try selecting the "Users" role and saving. 

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.0.11
- OS (e.g. from /etc/os-release): Windows 2008 R2
- Node.JS Version: 10.15.3 (x64)
- MongoDB Version: 4.0.6
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
This is going to be tricky because there was a typo in the initial install script which created a Users role by default instead of User. I have fixed this, but it would seem like your installation is affected by the fix in a way that the Users role is assigned to users which renamed the default role.

I have a couple of ways to fix this for your current case but will need to see a screenshot of your permission settings. 

Another way is if you're willing to send me a backup created with the Backup/Restore feature I can get the IDs of the roles and create a simple MongoDB script to run in mongo to reassign the roles to the correct id.

**Comment by polonel** [comment]
I'm going to add in a way to delete a user with tickets. It will ask to assign tickets from that user to a new user or delete the tickets. This is required because the tickets are linked to a user, and if that user cannot be found in the database it will crash when trying to pull user details.

**Comment by obutov** [comment]
I was able to fix the role assignment by executing API to re-assign to a correct role. 
Still what is the reason that "User" group doesn't show up in the dropdown when editing User Profile?

**Comment by polonel** [comment]
I can’t answer that without seeing the permission setup you have. The drop down pulls from the permissions.
