### ISSUE TITLE
departments not appearing

### ISSUE THREAD

**Issue by akhlaaqbadulla** [polonel/trudesk#200]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
installed the version 1.0.12 all went smoth but on restoring my update from another running instance. the departement page is blanc. alson when you edit groups the group memberlist is empty.

**What did you expect to happen**:
being able to create departements. manage my groups

**How to reproduce it (as minimally and precisely as possible)**:
fresh install v1.0.12 and upload v1.0.10 back up.

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.0.12
- OS (e.g. from /etc/os-release): ubuntu 18.04
- Node.JS Version: 11
- MongoDB Version: 4

**Comment by akhlaaqbadulla** [comment]
![Screenshot from 2019-05-10 16-52-50](https://user-images.githubusercontent.com/7328076/57528777-4428b680-7344-11e9-8e06-df4d2dbfb434.png)

**Comment by polonel** [comment]
Can you show the google console?
You may need to run `yarn run build`

**Comment by polonel** [comment]
Did this resolve the issue?

**Comment by akhlaaqbadulla** [comment]
![Screenshot from 2019-05-13 10-15-04](https://user-images.githubusercontent.com/7328076/57599552-22a81480-7568-11e9-80a3-bffff0275f52.png)
not it did not work still getting the same error.

**Comment by polonel** [comment]
So here is where the problem lies. You're restoring a v1.0.10 backup to a 1.0.12 instance. You've basically confused the server thinking it has already run the migrations when it booted up to 1.0.12 and then you restored a version before the migrations took place.

It doesn't have any departments in the database because departments didn't exist till 1.0.11.

You need to downgrade back to 1.0.10 and restore the 1.0.10 backup to the instance (at 1.0.10)
once it's fully restored. Upgrade the instance back to 1.0.12 and it will handle the department creation during the migration.

**Comment by akhlaaqbadulla** [comment]
Thank you very much. it worked.
