### ISSUE TITLE
after pm2 restart the app does not start

### ISSUE THREAD

**Issue by akhlaaqbadulla** [polonel/trudesk#232]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG  not sure
- [ ] FEATURE

**What happened**:
i upgraded to version 1.0.14 everything was running fine until i restart the app in pm2. after doing so it just gives me a 502 bad gateway error. and oddly in pm2 the number of restart just keeps on incrementing every time i check.

**What did you expect to happen**:
i got this form the log:
`{"message":"process name not found","stack":"Error: process name not found\n    at /opt/trudesk/node_modules/pm2/lib/API.js:1433:26\n    at /opt/trudesk/node_modules/pm2/lib/Client.js:696:12\n    at /opt/trudesk/node_modules/pm2-axon-rpc/lib/client.js:45:10\n    at Parser.<anonymous> (/opt/trudesk/node_modules/pm2-axon/lib/sockets/req.js:67:8)\n    at Parser.emit (events.js:193:13)\n    at Parser._write (/opt/trudesk/node_modules/amp/lib/stream.js:91:16)\n    at doWrite (_stream_writable.js:415:12)\n    at writeOrBuffer (_stream_writable.js:399:5)\n    at Parser.Writable.write (_stream_writable.js:299:11)\n    at Socket.ondata (_stream_readable.js:705:22)\n    at Socket.emit (events.js:193:13)\n    at addChunk (_stream_readable.js:295:12)\n    at readableAddChunk (_stream_readable.js:276:11)\n    at Socket.Readable.push (_stream_readable.js:231:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:154:17)","level":"error","timestamp":"2019-06-21T20:59:18.710Z"}`

**How to reproduce it (as minimally and precisely as possible)**:
upgrade from 1.0.10 to 1.0.14

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.0.14
- OS (e.g. from /etc/os-release): ubuntu 18.04
- Node.JS Version: 11
- MongoDB Version: 4
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Show me `pm2 status`

**Comment by akhlaaqbadulla** [comment]
![image](https://user-images.githubusercontent.com/7328076/59965458-4a06df80-951f-11e9-9382-e10e54cf76cb.png)

**Comment by polonel** [comment]
The app name must be `trudesk`. It can’t fin the process cause it’s looking for trudesk and you have named it `gaticket`

**Comment by akhlaaqbadulla** [comment]
i tried that as well. i still get the same issue..

**Comment by polonel** [comment]
How and where are you restarting the server anyway? I know the restart that is built in is hardcoded to look for the process `trudesk`. And since the error clearly states "Process not found" and you do not have a process in pm2 named trudesk. So not sure how that is possible.

https://github.com/polonel/trudesk/blob/bbce78692ee35eaf553fd15aba5a16168dad99f3/src/routes/index.js#L363

There are 90+ `v1.0.14` deployments active in the wild, and I'm not seeing any of these issues from any other users. These issues have to come from the customizations you have made.

![image](https://user-images.githubusercontent.com/626303/59965599-5585e680-94de-11e9-931d-939e50b4677e.png)

**Comment by akhlaaqbadulla** [comment]
its working now.. it was my nginx config as well issue..
thank you
