### ISSUE TITLE
Error Installation

### ISSUE THREAD

**Issue by kamalkech** [polonel/trudesk#29]
{"success":false,"error":{"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: trudesk.counters index: _id_ dup key: { : \"tickets\" }","op":{"_id":"tickets","next":1001,"__v":0}}}

any idea ???

**Comment by polonel** [comment]
This happened because the install process was either interrupted. It could have lost connection to the MongoDB server during the install. If you reboot the server and continues to run in install mode. You can try to run the install wizard as an existing MongoDB database, if that fails you will need to empty the database and start the install wizard again.
