### ISSUE TITLE
Cannot read property compile of undefined when I try sent e-mail

### ISSUE THREAD

**Issue by veffisot** [polonel/trudesk#333]
**Is this a BUG REPORT or FEATURE REQUEST?**:
- [X] BUG 
- [ ] FEATURE

**What happened**:
When trying to send, the password reset receives a 502 bad gateway error.

**Anything else we need to know?**:
I have configured the SMTP server in the settings, test connection shows success.
![obraz](https://user-images.githubusercontent.com/59391779/82213301-36711e00-9914-11ea-95ba-606262bb6600.png)

Other functions in Trudesk work (adding clients, users etc.)

**Environment**:
- Trudesk Version: 1.1.2
- OS (e.g. from /etc/os-release): Ubuntu 
- Node.JS Version: 10.15.2
- MongoDB Version: 4.2.6
- Is this hosted on cloud.trudesk.io: No

**Comment by teutat3s** [comment]
The same bug appeared here, in a from source install of the master branch with the latest commits. 
We start trudesk using the `pm2` process manager. After a little research it seems to be an issue with the beta mail templates.

Steps to reproduce:
- Install trudesk from source
- Set `NODE_ENV` to `development` for debug messages
- "Install" trudesk with `/install`
- Configure SMTP mail server
- Enable beta mail templates
- Customize password reset template (We just translated the text and saved the template)
- Log out and try the `Password reset` feature
- The error message mentioned above shows in `logs/output.log`

The following error shows in the `nginx` logs:
```
2020/07/13 21:46:34 [error] 17111#0: *5863 upstream prematurely closed connection while reading response header
from upstream, client: 11.22.33.44, server: help.example.com, request: "POST /forgotpass HTTP/2.0", 
upstream: "http://127.0.0.1:8118/forgotpass", host: "help.example.com", referrer: "https://help.example.com/"
```

At the same time `pm2` restarts trudesk completely, probably because of trudesk crashing.

After disabling the beta mail templates feature, password resets work as expected.

**Comment by teutat3s** [comment]
Would be great if @polonel could have a look and maybe consider reopening this issue?
