### ISSUE TITLE
Docker does not work

### ISSUE THREAD

**Issue by Teascade** [polonel/trudesk#391]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
Docker image straight up does not work. It prints out 
```
trudesk_1       | 2021-01-13T18:09:08: PM2 log: Launching in no daemon mode
trudesk_1       | 2021-01-13T18:09:08: PM2 log: App [trudesk:0] starting in -fork mode-
trudesk_1       | 2021-01-13T18:09:08: PM2 log: App [trudesk:0] online
```
But it is not serving anything. localhost:8118 does returns nothing.

**What did you expect to happen**:
Docker to work

**How to reproduce it (as minimally and precisely as possible)**:
Copy the file from `https://github.com/polonel/trudesk/blob/master/docker-compose.yml` to a folder
Run `docker-compose up`

**Anything else we need to know?**:

**Environment**: Docker
- Trudesk Version: polonel/trudesk:1, polonel/trudesk:1.1 and polonel/trudesk:1.0
- OS (e.g. from /etc/os-release): ArchLinux
- Node.JS Version: Whatever the docker images provide
- MongoDB Version: 3.6
- Is this hosted on cloud.trudesk.io: No

**Comment by formica2** [comment]
docker-compose still not working...

**Comment by pano9000** [comment]
still seeing the same issue with latest stable version, @Teascade did you manage find a fix for it? (sorry for digging up this dead issue)

**Comment by pano9000** [comment]
FYI: I managed to fix my issue, it was an error on my side.

The problem was: I had renamed the mongo service name inside my custom docker-compose.yml file:
e.g. instead of `mongo` as service name and container name, I renamed it to e.g. `trudesk-mongo`

HOWEVER I forgot to also update the value of the TD_MONGODB_SERVER env variable under the "trudesk" service accordingly, which is why the mongoDB connection of course failed, as it tried to connect to the DB using a non-existing hostname (`mongo` instead of `trudesk-mongo` in my case).

This was unfortunately not really visible in the console output, (i.e. what you usually check/see when running `docker logs`), but I only noticed it, after manually checking the trudesk log inside the container (`/usr/src/trudesk/logs/output.log`) (using `docker exec` to get a bash shell).
