### ISSUE TITLE
Admin creation not possible with docker & Fresh code base install (In trudesk) ! 

### ISSUE THREAD

**Issue by anujatshivlab** [polonel/trudesk#451]
**Is this a BUG REPORT or FEATURE REQUEST?**:
- [x] BUG 
- [ ] FEATURE

**What happened**:

When I try to create an admin then I got the following error.

 ```{"success":false,"error":{"errors":{"value":{"name":"ValidatorError","message":"Path `value` is required.","properties":{"message":"Path `value` is required.","type":"required","path":"value"},"kind":"required","path":"value"}},"_message":"settings validation failed","name":"ValidationError","message":"settings validation failed: value: Path `value` is required."}}```
 
 While retrying the same flow the getting following error.

`{"success":false,"error":{"driver":true,"name":"MongoError","index":0,"code":11000,"keyPattern":{"name":1},"keyValue":{"name":"gen:version"}}}`

**What did you expect to happen**:

Working admin profile

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a mongodb and trudesk container
2. Go to [http://localhost:8118/](http://localhost:8118/)
3. Fill in all informations
4. Submit
5. Error

**Environment**:

- Trudesk Version: Trudesk v1.1.10
- OS (e.g. from /etc/os-release): NAME="Ubuntu" VERSION="18.04 LTS"
- Node.JS Version: (docker)
- MongoDB Version: 4.0
- Is this hosted on cloud.trudesk.io: No

**Comment by JesusFregoso** [comment]
the first error its mention already here #446 

the mongo error is because you already try to create an installation.

enter into docker mongo bash and delete the trudesk database and start over from fresh install.

docker exec -it mongodb mongo

then inside mongo run this commands.
list databases to verify trudesk database

`db.adminCommand( { listDatabases: 1 } )`

then use trudesk

`use trudesk;`

then drop the database

`db.dropDatabase();`

start over with trudesk
