### ISSUE TITLE
Tickets created multiple times if fetched by mail check

### ISSUE THREAD

**Issue by csimlinger** [polonel/trudesk#456]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
When mails are sent to the mail check address, tickets are often created multiple times (duplicates)

**What did you expect to happen**:

Only one ticket should be created per email.

**How to reproduce it (as minimally and precisely as possible)**:

Send an email to the mail check, see if duplicated tickets show up.

**Environment**:
- Trudesk Version: 1.1.10
- OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- Node.JS Version: v16.12.0
- MongoDB Version: v4.4.10
- Is this hosted on cloud.trudesk.io: no

I experience the explained issue.
Sometimes mails are not at all converted to tickets but deleted from my inbox (therefore they must be somehow processed).

One further question: is it possible to merge tickets?

Thanks a lot!

**Comment by polonel** [comment]
What mail provider are you using? This could be caused by latency where trudesk thinks it processed and deleted the email but actually didn't. 

Trudesk takes all unread emails and tries to turn them into a ticket. If you do not have the **Create Account** checked then it must have a matching user with the same FROM address or it will delete the email and no ticket will be processed. (this is to help combat spam tickets.)
