### ISSUE TITLE
Potential support for push notifications

### ISSUE THREAD

**Issue by rusty1281** [polonel/trudesk#533]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [X] FEATURE

Wondering if support for push notifications or webhooks would be an option? Pushover would be a push platform as an example so that instead of using email notifications on changes and new tickets, we get a push or webhook action.

Tnx in advance!

ps - a very nice platform that I will for sure run and evaluate for some time. Using it already in "prod" for internal usage. [Wrote a short intro](https://www.blackvoid.club/trudesk-self-hosted-task-management-platform/) for it over at my site to promote it as well. Good luck with it going forward!

**Comment by polonel** [comment]
Trudesk had a native iOS and Android back years ago with push notifications. I couldn't find time to keep it updated solo and Apple ultimately removed the app from the AppStore due to its use of an outdated API. 

I have since shut down the push service server that was running. I had hoped to recreate an updated native app, but Trudesk Inc was formed and a cloud version went into development, the native app is being reserved for the hosted cloud version. 

I still solo maintain the open source community edition and am not part of the cloud version of trudesk. The cloud version has a larger feature set. All of which are still in active development. 

I'll see if webhooks are something that's doable.  😃 

PS: Thank you for the write-up. I appreciate the support.

**Comment by rusty1281** [comment]
> I'll see if webhooks are something that's doable. 

Wicked! Tnx again!

**Comment by Chesterguan** [comment]
I will vote for the feature as well. I will try to add webhooks in my fork. let's see

Nice job @polonel

**Comment by polonel** [comment]
Planned v2
