### ISSUE TITLE
Error on create new Public Tickets

### ISSUE THREAD

**Issue by 0toshigami** [polonel/trudesk#611]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
- An error occurred in a new fresh Docker installation when "Allow Public Tickets" was enabled.
- When calling the API `/api/v1/public/tickets/create`, a 400 Bad Request is returned.
- The error message in the response is "tickets validation failed: status: Path 'status' is required."

**Environment**:
- Trudesk Version: 1.2.8
- OS: WSL
- Node.JS Version: 16.14-alpine
- MongoDB Version: mongo:5.0-focal
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
To confirm this **ONLY** happen with Allow Public Tickets enabled?

**Comment by 0toshigami** [comment]
@polonel I can create a ticket normally within the dashboard interface

**Comment by polonel** [comment]
This is likely related to the status changes. Investigating...

**Comment by jnijland** [comment]
I've got the same issue on a completely fresh install. Public tickets are not working for me.

```success: false, error: "tickets validation failed: status: Path `status` is required."}```

**Comment by kareem-abdul** [comment]
This issue still exists, I think the problem is that the `status` field in the ticket object is marked as required
https://github.com/polonel/trudesk/blob/ad4c42c3b88c42d90e41b3615f1ee205925ad03e/src/models/ticket.js#L95-L100
and a default status is not being set in the public ticket creation API
https://github.com/polonel/trudesk/blob/ad4c42c3b88c42d90e41b3615f1ee205925ad03e/src/controllers/api/v1/tickets.js#L635-L644
