### ISSUE TITLE
Development enviroment

### ISSUE THREAD

**Issue by fyodorr** [polonel/trudesk#612]
Hi,

First I want to thank you for your time and effort put into this project. Wonderful work.

I'm setting up a development environment for myself. Been using the grunt for this and the next branch. I have some problems getting it to work though. The installation script is running, but it doesn't populate any users and I got the 11000 error. Got it to work eventually but when I try to log on to the build, the account is empty in MongoDB.

I'm not so used to ts and js, I've been a low-level programmer for too long 😞 

Is there some easier way to set up a development environment and populate the DB by a script or how do you set up your environment?

**Comment by polonel** [comment]
Which OS are you running? Sometimes Windows can be a bit tricky to get going.
I develop on Windows but run my MongoDB and Elasticsearch on a Virtualbox VM.

**Comment by fyodorr** [comment]
Currently, using Ubuntu 22.04 LTS Desktop in Vmware Workstation. Used Virtualbox, but it had problems with the AVX and getting the DB running.

Maybe should try your setup. Is there some prefered version of MongoDB that I should use?

**Comment by polonel** [comment]
Ubuntu 22.04 in VMWare is fine. My Mongo version is v5.0.11.

The issue is once you have a failed installed with the install script it usually will keep failing because it already contains some data. Sometimes development env will need to wipe my database when testing certain things.

This will drop all collections into a database. **MAKE SURE YOU ARE RUNNING THIS ON YOUR DEV ENV ONLY!**
```
db.getCollectionNames().forEach(function(c) { if (c.indexOf("system.") == -1) db[c].drop(); })
```

Once I have the database setup I boot up the trudesk server with `grunt` and if there is no `config.yml` file it should run the Install Server.

Once the Install Server is running I just let that handle the population of the database
