### ISSUE TITLE
I want to start contributing

### ISSUE THREAD

**Issue by bhanuAtWork** [polonel/trudesk#637]
**Feature Request**:

**I am an active developer with a strong passion for working with JavaScript. I know reactJs and Nodejs very well. I am eager to contribute to this project in any way I can. I initially attempted to make a simple label change as a starting point, but unfortunately, the changes did not take effect.**

**Steps I did are**:

1. docker-compose up -d trudesk
2. docker-compose up -d elasticsearch
3. docker-compose up -d mongo
4. In src/client/components/Nav/Sidebar/index.jsx change something like Customer Groups to XYZ Groups I save the changes but on view sidebar nothing got reflected. Can you tell how can I get started ? 

Please let me know if I am missing something. Let me know any other development branch from where I can checkout and start contributing.

**Comment by girishgl** [comment]
I am also facing the same issue. My changes are not getting reflected

**Comment by polonel** [comment]
I react components are built using Webpack. Making changes within the docker container is difficult because build files are prebuilt during the build of the docker image. 

To set up a dev env, you should clone the repo directly and make the changes. A development server can easily spin up with one command: `grunt`

No code is developed directly on the `master` branch. The develop branch is in maintenance mode only right now as a feature branch (`next`) is underway for version `1.3`
