### ISSUE TITLE
Site don't work on mobile

### ISSUE THREAD

**Issue by gray1881** [polonel/trudesk#661]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
When I use site in Mobile, it just show a text and get refresh unstoply

**What did you expect to happen**:

I expected site work on mobile fine.

**How to reproduce it (as minimally and precisely as possible)**:

I think you could just install it on a Ubuntu 20 server, I install it twice and it didn't work.

**Anything else we need to know?**:

I don't use ssl and I don't use a domain.

**Environment**:
- Trudesk Version: I'm not sure, probably last version because I used this script:
- curl -L -s https://storage.trudesk.io/install/ubuntu-1.2.sh | sudo bash
- 
- OS (e.g. from /etc/os-release): Ubuntu 20
- Node.JS Version: I didn't install it, script did this.
- MongoDB Version: I didn't install it, script did this.
- Is this hosted on cloud.trudesk.io: no, I used a server from hetzner.

**Comment by polonel** [comment]
The mobile site was disabled until a rewrite was completed. It was using an older ionic version that was unstable and had some unfixed security vulnerabilities.

**Comment by anuj-cogg** [comment]
@polonel, I am experiencing the exact same issue, I am using 
`wget https://raw.githubusercontent.com/polonel/trudesk/master/docker-compose.yml` docker compose. 

Whenever I try to reduce the screen size, the application goes into endless refresh loop(sometimes with a text - 'View Mobile Site' in the middle of the screen). 
Just wanted to know if this issue is fixed or it is planned to be fixed in future?
