### ISSUE TITLE
Install script isnt working on fresh Ubuntu 16.04 install

### ISSUE THREAD

**Issue by JohnShortland** [polonel/trudesk#68]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Couldn't connect; make sure connection is correct.

**What did you expect to happen**:
Installation to proceed to next step

**How to reproduce it (as minimally and precisely as possible)**:
Fresh Ubuntu 16.04 install
Ran: curl -L -s http://www.trudesk.io/install/install_ubuntu.sh \| sudo bash
Selected to Install deps via script and mongodb locally via script
Go to localhost:8118
Click Test Connection

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: Version of the script
- OS (e.g. from /etc/os-release): NAME="Ubuntu" VERSION="16.04.4 LTS (Xenial Xerus)"
- Node.JS Version: v8.11.1
- MongoDB Version: v3.6.3
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
@JohnShortland I'm having trouble reproducing. I have deployed a new instance on AWS of Ubuntu 16.04.4 LTS and ran `curl -L -s http://www.trudesk.io/install/install_ubuntu.sh | sudo bash` as soon as I logged in for the first time. I selected `Y` to install deps and `Y` to install mongodb. I was able to load up the install wizard and click `Test Connection` and it proceeded as it should. 

The only difference from your steps was I could not access the server through localhost as it does not have a gui.

In case you haven't seen the install script video [https://www.youtube.com/watch?v=Yq1UWmdRcwg](https://www.youtube.com/watch?v=Yq1UWmdRcwg) shows what a normal run of the script should look like.

**Comment by JohnShortland** [comment]
@polonel I used AWS also and did the exact same as you did, twice. I'll give it a try now again and see if it works.

**Comment by JohnShortland** [comment]
@polonel Did it again to test I deployed a t2.micro Ubuntu 16.04.4 LTS, logged in and ran curl -L -s http://www.trudesk.io/install/install_ubuntu.sh. The same issue has occured once the script completes. Attached is the script output and a screenshot of the error.

<img width="1124" alt="capture" src="https://user-images.githubusercontent.com/7707935/38438986-06ae2e2a-39d4-11e8-8e74-2c53f40bc55a.PNG">
[script_output.txt](https://github.com/polonel/trudesk/files/1885251/script_output.txt)

**Comment by polonel** [comment]
@JohnShortland So I see a couple of things that are different than when I run the same script, and it has to do with the EU repositories. Do you mind giving it a try in the US-EAST region?

**Comment by polonel** [comment]
@JohnShortland I deployed an instance to EU-West-2 (London) and all went well. I have left the install wizard uncompleted if you wish to take a look. [http://35.178.165.126:8118](http://35.178.165.126:8118)

**Comment by JohnShortland** [comment]
@polonel Just done it in US-EAST-1 and it works. What have you spotted that is different so I can try and fix manually in eu-west-1.

**Comment by polonel** [comment]
@JohnShortland 
Here is the server instance in EU-WEST-2 running:
![sever](https://user-images.githubusercontent.com/626303/38440482-937f50ce-39af-11e8-8834-cadffaa49a6c.PNG)

These are the security group settings I use for a trudesk deployment to AWS, just to verify they are the same.
![capture](https://user-images.githubusercontent.com/626303/38440479-91c0f9f4-39af-11e8-906c-c6b0ebf006c1.PNG)

What I noticed was it had failed to validate the checksum of some packages when pulling from the EU repos and thus didn't install them (or installed stale packages), but I do not think thats the actually cause now after I deployed to London and it seemed to work. I'm trying other regions as well. 

I want to reproduce so I can find the root of the problem. 
(Also note that I have never deployed to regions outside the US so my AWS console is clean when I switch regions)

**Comment by JohnShortland** [comment]
@polonel 
My setup if you want to replicate it is, a private subnet with an ec2 t2.micro running ubuntu 16.04, then an elb pointing to the ec2 instance. For security groups even selecting all traffic and allowing 0.0.0.0/0 still produces the error.

**Comment by polonel** [comment]
Thanks for the information. I will test when using an ELB. I haven't tested going through the ELB yet.

**Comment by JohnShortland** [comment]
@polonel 

Its the ELB that is the issue, I think. I created a new machine in a public subnet and without the ELB and it works, however it is not a great solution as the idea of having it behind the ELB is that it can be kept in a private subnet and much more secure. Any ideas what is causing it?

**Comment by polonel** [comment]
@JohnShortland 
I have some ideas. I'm going to do some testing today with your setup and report back. I think it has to do with the way trudesk detects the url/server/port it's running on and tries to communicate with itself but fails to report back to the client side correctly because of the ELB proxy. 

I'll give you a ping with my findings shortly.

**Comment by polonel** [comment]
@JohnShortland 
I have tested with ELB in both private and public subnet and I can't get it to fail. How many instances are you running behind the ELB? 2? 
I did notice that the install script/communication could fail if it sent the ajax `test connection` POST to the other instance. It wouldn't know which instance to forward the response back to and would timeout.
_but this was only an issue with 2 instances or more_

I tested with the following:
ELB - [http://Trudesk-ELB-1715517370.us-east-1.elb.amazonaws.com](http://Trudesk-ELB-1715517370.us-east-1.elb.amazonaws.com)
Instance 1 - MongoDB Server (10.10.1.5)
**The Following 2 instances are in a Target Group Together**
Instance 2 - Trudesk Server (10.10.1.6)
Instance 3 - Trudesk Server (10.10.1.7)

All created on a new VPC with a Private Subnet only.
_Note: I'll leave the ELB address up for a couple more hours before I delete everything._

I was having a separate issue (which I'm fully aware happens) with the WebSocket constant disconnect because the proxy doesn't fully support the WebSocket and `X-Forwarded-For` header. (But that's a totally separate problem)

Now if you want to discuss running multiple instances of the trudesk server with a shared MongoDB database. This has been tested with Docker containers and kubernetes and its what my trudesk cloud platform is running on.

**Comment by polonel** [comment]
I actually just read some of your edits.

Usually, the best practice way to create this setup is to have the ELB point to 2+ NGINX servers that can communicate with the Trudesk Servers in the private subnet. (ACL with the source of the NGINX servers to only allow those two servers to talk to the private subnet.) I've personally have no done this with ELB before but have completed it with GCP.

**Comment by polonel** [comment]
Just to document: [https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Scenario2.html](https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Scenario2.html)

**Comment by GangaramD** [comment]
Hi @polonel  New to Containers and kubernetes, so i would request if you can share a link or a doc which guides in creating configurations ( Deployments and services) in kubernetes to  install trudesk and connect it to the mongodb DB.

Thanks In Advance!!!
