### ISSUE TITLE
I want to put trudesk on my server

### ISSUE THREAD

**Issue by jonasaraujo96** [polonel/trudesk#88]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [X] FEATURE

**What happened**:
When I run "npm run build" a folder with the compiled project is not created

**What did you expect to happen**:
I want to put the project on the server to be accessed through a domain, for example "trudesk.tickets.com.br"

**How to reproduce it (as minimally and precisely as possible)**:
I tried to put the whole folder on the server

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: last version
- OS (e.g. from /etc/os-release): Linux Mint
- Node.JS Version: 8.10.0
- MongoDB Version: 3.6.7
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Trudesk itself has a built-in web server once its running. You can access the instance at `http://ipaddress:8118`

In order to access the site on port 80 with a domain name, you will need to set up a reverse proxy (nginx). The trudesk documentation gives an example of doing this, [Trudesk Nginx Reverse Proxy Documentation](https://trudesk.io/v1/guide/installation.html#Reverse-Proxy-Nginx)

For additional documentation on nginx, please review nginx documentation: [https://nginx.org/en/docs/](https://nginx.org/en/docs/)

**Comment by jonasaraujo96** [comment]
With this, people outside the locall network will be able to access the site?

**Comment by jonasaraujo96** [comment]
thank you!

Another question, what do I need to add a field to the expected end date of the ticket?

**Comment by polonel** [comment]
Currently, it does not support adding custom fields to the Tickets. This is being worked on and is a planned feature in the near future.
