### ISSUE TITLE
I need to know about TPS and Mailer Setup

### ISSUE THREAD

**Issue by srladuani** [polonel/trudesk#99]
**Anything else we need to know?**:
Hello @polonel , @all
I have download source code and setup on my local machine. Can you please help me to know about the Mail settings?
And, also please guide me about TPS. How will I setup firebase for sending push notifications?

Thanks and Regards,
Sarwan Kumar

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io: No, I have download source code & setup on my local machine.

**Comment by srladuani** [comment]
@polonel for email, I have setup SMTP and its working.
But, for push notifications it requires to setup only for `http://push.trudesk.io/api/pushNotification`.
I am setting it up on my local machine from source code. So, How can I do it?
Thanks.

**Comment by polonel** [comment]
The trudesk push service is used for the native Android and iOS apps. Both apps are waiting "in review" by the app stores. The trudesk push server is a middleman to handle the push notifications due to the way iOS push notifications work and the fact that the native apps can talk to any trudesk server. Once you the native apps are released by the app store, you simply just create a free account at [http://push.trudesk.io](http://push.trudesk.io) and then input your username and API Key into your trudesk server instance and push notifications to the mobile apps will start to work. 

In order to use `firebase` for web pushes, you would need to modify the core code to route to your firebase server instead of the trudesk push server. This is not recommended because the official native mobile apps will not support this.

**Comment by srladuani** [comment]
Alright! thanks @polonel
